spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_order_dev
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true